Added new feature of Cricket
swapagarwal/JARVIS-on-Messenger pull request #393
Opened 2018-03-24 11:21 UTC by shubhsherl

#### Changes proposed in this pull request:

-Proposed to add a new feature of Cricket-Livescores

**Fixes**: #

2018-03-24 11:21 UTC, swapagarwal commented
Thank you for taking the time to contribute! This is sincerely appreciated. 😇

(Powered by [GitMate.io](https://gitmate.io))

<!-- Timestamp signature `Thank you for taking the time to contribute! This is sincerely appreciated. 😇:1ezhEM:PAu78WbvQAb4VtT74XJO-Ad2kEw` -->

2018-03-24 16:56 UTC, swapagarwal commented
Can you share a sample output that this module will give?

2018-03-24 16:58 UTC, swapagarwal requested changes

2018-03-24 16:58 UTC, swapagarwal commented on code.py
> +import json
Why is this file needed?

2018-03-24 17:11 UTC, shubhsherl commented
Sorry about code.py, I forgot to delete that.

2018-03-24 17:15 UTC, shubhsherl commented
input: cricket
Output:
`1st Test
NZ vs ENG
NZ	233/4
ENG	58/10
NZ lead by 175 runs
**********
3rd Test
RSA vs AUS
RSA	238/5
AUS	255/10
RSA lead by 294 runs
**********
3rd ODI (ICC Championship match)
SLW vs PAKW
SLW	107/10
PAKW	215/9
Pak Women won by 108 runs
**********
3rd ODI (ICC Championship match)
SLW vs PAKW
SLW	107/10
PAKW	215/9
Pak Women won by 108 runs
**********
3rd One-day
NORTH vs SOUTH
SOUTH	204/10
NORTH	296/8
North won by 92 runs
**********
<button ="Cricbuzz Live">
`

2018-03-27 18:49 UTC, shubhsherl commented
@swapagarwal is the changes in modules are fine to merge?

2018-04-07 09:55 UTC, shubhsherl commented
@swapagarwal, any suggestion over this module?

2026-06-26 05:53 UTC, closed without merging